# Header
menu:
  Home: /
  Archives: /archives

# Default post title
default_post_title: ooooooooops

# Default post cover index page
#default_cover_index: "http://placehold.it/450x450"
default_cover_index: "https://placeholdit.imgix.net/~text?txtsize=52&bg=000000&txtclr=ffffff&txt=-.-.-.--&w=450&h=450&fm=png"

# Default post cover index page
#default_cover_detail: "http://placehold.it/1300x500"
default_cover_index: "https://placeholdit.imgix.net/~text?txtsize=52&bg=000000&txtclr=ffffff&txt=-.-.-.--&w=1300&h=500&fm=png"

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: javascript:;
facebook_url: javascript:;
behance_url: javascript:;
googleplus_url: javascript:;
dribble_url: javascript:;
rss_url: javascript:;
